name = "anemone-duette"
compatibility_date = "2025-07-21"
main = "src/worker.js"
assets = { directory = "dist", binding = "ASSETS", not_found_handling = "single-page-application", run_worker_first = ["/api/*"] }
